spring:
  profiles:
    active: ${RUNTIME_MODE}

springdoc:
  swagger-ui:
    path: /doc

feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  okhttp:
    enabled: true