spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddd_attendance?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: test4n23ub3n4uigb80hn08sdhncv803nf2308bn32g
  expires: ${JWT_EXPIRES}